## Cartesian Product

In [1]:
import pandas as pd
import numpy as np

In [2]:
table1 = pd.DataFrame([
    [10, 'a', 5],
    [15, 'b', 8],
    [25, 'a', 6],
], columns=['P', 'Q', 'R'])

table2 = pd.DataFrame([
    [10, 'b', 6],
    [15, 'c', 3],
    [10, 'b', 5],
], columns=['A', 'B', 'C'])

cp = table1.merge(table2, how='cross')
cp

    P  Q  R   A  B  C
0  10  a  5  10  b  6
1  10  a  5  15  c  3
2  10  a  5  10  b  5
3  15  b  8  10  b  6
4  15  b  8  15  c  3
5  15  b  8  10  b  5
6  25  a  6  10  b  6
7  25  a  6  15  c  3
8  25  a  6  10  b  5

In [3]:
cp[cp.P==cp.A]

    P  Q  R   A  B  C
0  10  a  5  10  b  6
2  10  a  5  10  b  5
4  15  b  8  15  c  3

In [4]:
cp[cp.Q==cp.B]

    P  Q  R   A  B  C
3  15  b  8  10  b  6
5  15  b  8  10  b  5

In [5]:
cp[(cp.P==cp.A) & (cp.R==cp.C)]

    P  Q  R   A  B  C
2  10  a  5  10  b  5

In [6]:
cp[(cp.P==cp.A) | (cp.R==cp.C)]

    P  Q  R   A  B  C
0  10  a  5  10  b  6
2  10  a  5  10  b  5
4  15  b  8  15  c  3
6  25  a  6  10  b  6

## Real-Table Example 0f Joins

In [25]:
product_table = pd.read_csv('beton24_csvs.csv/hamkorqurilish_main_table_product.csv', header=None, usecols=[0, 1, 5, 6], names
                            =['Pnumber', 'PName', 'Price', 'Cno'])
product_table = product_table.iloc[:10, :]

In [28]:

category_table = pd.read_csv('beton24_csvs.csv/hamkorqurilish_main_table_type_product.csv', header=None, usecols=[0, 1, 6], names
                            =['Cno', 'CName', 'Mno'])
category_table = category_table[category_table.Cno < 12]
category_table

   Cno                CName  Mno
0    1      ФБС (Цем 32.5Н)    5
1    2      ЛМП (Цем 32.5Н)    5
2    4                БЕТОН    4
3    5    ОПОРА (Цем 32.5Н)    5
4    6            Брусчатка    3
5    8  КОЛОННА (Цем 32.5Н)    5
6    9  Колодцы (Цем 32.5Н)    5
7   11    Лотки (Цем 32.5Н)    5

In [27]:

measurement_table = pd.read_csv('beton24_csvs.csv/hamkorqurilish_main_table_olchov.csv', header=None, usecols=[0, 1], names
                            =['Mno', 'Mname'])
measurement_table.head(5)

   Mno    Mname
0    1     метр
1    2       кг
2    3  квадрат
3    4      куб
4    5     дона

In [32]:
product_table.merge(category_table, on="Cno", how='inner')\
            .merge(measurement_table, on="Mno", how='inner')\
            .drop(columns=['Mname_y', 'Cno', 'Mno'])\
            .rename(columns={'Mname_x': 'Mname'})

   Pnumber               PName   Price              CName Mname
0        1         24.4.6 М200  275000    ФБС (Цем 32.5Н)  дона
1        2         12.4.6 М200  135000    ФБС (Цем 32.5Н)  дона
2        3                ЛК-6  720000  Лотки (Цем 32.5Н)  дона
3        4            ЛБД 300   250000  Лотки (Цем 32.5Н)  дона
4        6    БЕТОН М100 В7.5   350000              БЕТОН   куб
5        7      БЕТОН М150 В10  380000              БЕТОН   куб
6        8      БЕТОН М200 В15  410000              БЕТОН   куб
7        9     БЕТОН М250 B20   440000              БЕТОН   куб
8       10   БЕТОН М300 В22,5   580000              БЕТОН   куб